inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Include:
    - "**/*.rb"
    - "**/*.gemfile"
    - "**/*.gemspec"
    - "**/*.rake"
    - "**/*.ru"
    - "**/*.ruby"
    - "**/*.spec"
    - "**/*.thor"
    - "**/.irbrc"
    - "**/.pryrc"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - ".git/**/*"
    - "bin/*"
    - "db/seeds.rb"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Rails:
  Enabled: true

Layout/LineLength:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
